import { NavItem, Feature, ServiceCategory } from '../types';

export const NAVIGATION_ITEMS: NavItem[] = [
  { label: 'Home', href: '#home' },
  { label: 'Services', href: '#services' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
];

export const FEATURES_DATA: Feature[] = [
  {
    id: 'feature-1',
    title: 'Trusted Professionals',
    description: 'All service providers are vetted and verified for quality and reliability.',
    icon: 'Shield',
  },
  {
    id: 'feature-2',
    title: 'Quick Response',
    description: 'Get connected with service providers in your area within minutes.',
    icon: 'Zap',
  },
  {
    id: 'feature-3',
    title: 'Competitive Pricing',
    description: 'Compare quotes from multiple providers to get the best deal.',
    icon: 'DollarSign',
  },
  {
    id: 'feature-4',
    title: 'Easy Booking',
    description: 'Book services directly through our platform with just a few clicks.',
    icon: 'Calendar',
  },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'home-services',
    title: 'Home Services',
    icon: 'Home',
    emoji: '🏠',
    color: 'bg-blue-50 border-blue-200',
    services: [
      { id: 'hvac', name: 'HVAC Repair & Installation' },
      { id: 'plumbing', name: 'Plumbing Services' },
      { id: 'appliance', name: 'Appliance Repair' },
      { id: 'roofing', name: 'Roofing Services' },
      { id: 'windows', name: 'Window & Door Replacement' },
      { id: 'garage', name: 'Garage Door Repair' },
      { id: 'pest', name: 'Pest Control' },
      { id: 'water', name: 'Water Damage Restoration' },
      { id: 'foundation', name: 'Foundation Repair' },
      { id: 'gutter', name: 'Gutter Installation & Cleaning' },
      { id: 'lawn', name: 'Lawn Care & Landscaping' },
      { id: 'carpet', name: 'Carpet Cleaning' },
      { id: 'solar', name: 'Solar Panel Installation' },
      { id: 'security', name: 'Home Security Systems' },
    ],
  },
  {
    id: 'health-wellness',
    title: 'Health & Wellness',
    icon: 'Heart',
    emoji: '🦷',
    color: 'bg-green-50 border-green-200',
    services: [
      { id: 'dental-implants', name: 'Dental Implants' },
      { id: 'dentistry', name: 'General Dentistry' },
      { id: 'braces', name: 'Braces & Invisalign' },
      { id: 'lasik', name: 'Vision Correction (LASIK)' },
      { id: 'hearing', name: 'Hearing Aids' },
      { id: 'rehab', name: 'Addiction Rehab Centers' },
      { id: 'mental', name: 'Mental Health Counseling' },
      { id: 'weight', name: 'Weight Loss Clinics' },
      { id: 'therapy', name: 'Physical Therapy' },
      { id: 'medical-alert', name: 'Medical Alert Systems' },
    ],
  },
  {
    id: 'insurance',
    title: 'Insurance Services',
    icon: 'Shield',
    emoji: '📞',
    color: 'bg-purple-50 border-purple-200',
    services: [
      { id: 'auto-insurance', name: 'Auto Insurance' },
      { id: 'health-insurance', name: 'Health Insurance' },
      { id: 'medicare', name: 'Medicare Insurance' },
      { id: 'life-insurance', name: 'Life Insurance' },
      { id: 'final-expense', name: 'Final Expense Insurance' },
      { id: 'homeowners', name: 'Homeowners Insurance' },
      { id: 'renters', name: 'Renters Insurance' },
    ],
  },
  {
    id: 'finance-legal',
    title: 'Finance & Legal',
    icon: 'Scale',
    emoji: '💰',
    color: 'bg-amber-50 border-amber-200',
    services: [
      { id: 'tax-relief', name: 'Tax Relief Services' },
      { id: 'credit-repair', name: 'Credit Repair Services' },
      { id: 'debt-settlement', name: 'Debt Settlement' },
      { id: 'personal-loans', name: 'Personal Loans' },
      { id: 'business-loans', name: 'Business Loans' },
      { id: 'legal-help', name: 'Legal Help (Divorce, DUI, Injury)' },
      { id: 'bankruptcy', name: 'Bankruptcy Lawyers' },
      { id: 'ssdi', name: 'SSDI (Social Security Disability Insurance)' },
      { id: 'workers-comp', name: 'Workers Compensation Attorneys' },
    ],
  },
  {
    id: 'automotive',
    title: 'Automotive Services',
    icon: 'Car',
    emoji: '🚗',
    color: 'bg-red-50 border-red-200',
    services: [
      { id: 'auto-glass', name: 'Auto Glass Replacement' },
      { id: 'auto-warranty', name: 'Auto Warranty' },
      { id: 'car-insurance', name: 'Car Insurance' },
      { id: 'auto-locksmith', name: 'Auto Locksmith' },
      { id: 'car-shipping', name: 'Car Shipping' },
      { id: 'junk-car', name: 'Junk Car Removal' },
    ],
  },
  {
    id: 'real-estate',
    title: 'Real Estate & Moving',
    icon: 'Building',
    emoji: '🏠',
    color: 'bg-teal-50 border-teal-200',
    services: [
      { id: 'mortgage-refinance', name: 'Mortgage Refinance' },
      { id: 'reverse-mortgage', name: 'Reverse Mortgage' },
      { id: 'home-buying', name: 'Home Buying Assistance' },
      { id: 'moving', name: 'Moving Services' },
      { id: 'rent-to-own', name: 'Rent-to-Own Homes' },
    ],
  },
  {
    id: 'tech-telecom',
    title: 'Tech & Telecom',
    icon: 'Smartphone',
    emoji: '📱',
    color: 'bg-indigo-50 border-indigo-200',
    services: [
      { id: 'internet-cable', name: 'Internet & Cable Deals' },
      { id: 'mobile-plans', name: 'Mobile Plans & SIM Cards' },
      { id: 'tech-support', name: 'Tech Support Services' },
      { id: 'satellite-tv', name: 'Satellite TV Services' },
    ],
  },
];

export const SITE_CONFIG = {
  name: 'ClickSmart',
  description: 'Your trusted marketplace for professional services',
  url: 'https://clicksmart.com',
  ogImage: '/og-image.png',
  creator: '@clicksmart',
}; 